#!/bin/bash
set -e
#set -v
MYTMPDIR=`mktemp -d`
trap "rm -rf $MYTMPDIR" EXIT
cd /usr/src/app
MODEL=${1:-connemara}
shift||true

phantomjs record-model-v.js $MYTMPDIR $MODEL $@
ffmpeg -y -c:v png -f image2 -s 800x600 -start_number 61 -i /$MYTMPDIR/img%07d -r 30 -c:v libx264 -pix_fmt yuv420p -movflags +faststart $MYTMPDIR/recording.mp4
mkdir -p /var/www/html/model-v/$MODEL
TARGET="${MODEL}-`date +%Y-%m-%d`.mp4"
mv $MYTMPDIR/recording.mp4 /var/www/html/model-v/$MODEL/$TARGET
ln -s -f /var/www/html/model-v/$MODEL/$TARGET /var/www/html/model-v/$MODEL/latest.mp4
